[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 120
target-version = ["py38"]

[tool.mypy]
python_version = "3.8"
mypy_path = "src"

# show error messages from unrelated files
follow_imports = "normal"

# suppress errors about unsatisfied imports
ignore_missing_imports = true

# be strict
warn_return_any = true
warn_no_return = true
warn_redundant_casts = true
warn_unused_ignores = true
