[tool.black]
line-length = 120
target-version = ["py38"]

[tool.mypy]
python_version = "3.8"
mypy_path = "src"
ignore_missing_imports = true
warn_return_any = true
warn_no_return = true
warn_redundant_casts = true
warn_unused_ignores = true
